language: node_js
node_js:
  - "5.0"
  - "node"
sudo: false
cache:
   directories:
     - node_modules
     - chrome-linux
     - extension/node_modules
before_script:
  - npm --prefix ./extension install ./extension
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./test/download-chrome.sh
  - start-stop-daemon --start --background --exec $(pwd)/launch-chrome.sh -- --disable-setuid-sandbox
  - sleep 5
script:
  - npm run lint
  - npm run unit
  - npm run closure
  - npm run smoke
  - (cd extension && gulp build)
